---
name: traefik
version: 1.0.0
iteration: 4
epoch: 1
license: MIT
vendor: Emile Vauge
architecture: x86_64
type: rpm
url: https://github.com/EmileVauge/traefik
description: Træfɪk, a modern reverse proxy

# this field means nothing now that they've switched from numbers to git hashes.
# However, we need to keep it around until the version actually changes. Bump
# this and iteration until then.
epoch: 413

dependencies:
  - libcap
  - traefik-config-scripts >= 1.0.0-3

resources:
  - url: https://github.com/containous/traefik/releases/download/v1.0.0/traefik_linux-amd64
    hash-type: sha1
    hash: fdba2e3f2ec435b30f3bcd963460b659883edb28

targets:
  # base
  - src: '{{.BuildRoot}}/traefik_linux-amd64'
    dest: /usr/bin/{{.Name}}
  - src: '{{.SpecRoot}}/{{.Name}}.service'
    dest: /etc/systemd/system/{{.Name}}.service
    template: yes
  - src: "{{empty}}"
    dest: /var/log/{{.Name}}
  - src: "{{empty}}"
    dest: /var/log/{{.Name}}/archive

scripts:
  before-install: |
    getent group {{.Name}} > /dev/null || groupadd -r {{.Name}}
    getent passwd {{.Name}} > /dev/null || \
        useradd -r \
                -g {{.Name}} \
                -d /etc/{{.Name}} \
                -s /sbin/nologin \
                -c "{{.Name}} user" \
                {{.Name}}

  after-install: |
    chown -R root:root /etc/{{.Name}}
    chown -R {{.Name}}:{{.Name}} /var/log/{{.Name}}

    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    systemctl enable /etc/systemd/system/{{.Name}}.service 2>/dev/null
    systemctl start {{.Name}}.service

    traefik-global --port=80 --grace-time-out=10
    traefik-web --address=:8080

  after-upgrade: |
    chown -R {{.Name}}:{{.Name}} /var/log/{{.Name}}

    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    chown -R root:root /etc/traefik
    systemctl daemon-reload
    systemctl restart {{.Name}}.service

  before-remove: |
    systemctl stop {{.Name}}.service
    systemctl disable {{.Name}}.service 2>/dev/null

  after-remove: |
    systemctl daemon-reload

extra-args: |
  --rpm-os linux
  --rpm-auto-add-directories
  --rpm-auto-add-exclude-directories /etc/systemd
  --rpm-auto-add-exclude-directories /etc/systemd/system
